### ISSUE TITLE
Add .-epub-media-overlay-active to screen.css and epub.css

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-classic-theme#1]
_From @arthurattwell on November 23, 2015 15:7_

To allow for future sync with audio/SMIL, add styling for -epub-media-overlay-active. e.g.

``` css
.-epub-media-overlay-active {
   background-color: #FFFF99;
}
```

_Copied from original issue: electricbookworks/electric-book-workflow#6_
